# Generated by Django 4.0.4 on 2022-04-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_like_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='created',
        ),
    ]
