# Generated by Django 4.0.4 on 2022-04-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_created_at_dislike_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['created']},
        ),
    ]
