# Generated by Django 4.0.4 on 2022-04-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='dislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='posts.post'),
        ),
    ]
