# Generated by Django 4.0.4 on 2022-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_dislike_user_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
